DATASET:
  root_dataset: "./data/"
  list_train: "./data/habitattraining.odgt"
  list_val: "./data/habitatvalidation.odgt"
  num_class: 101
  imgSizes: (512, 512)
  imgMaxSize: 512
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "c1"
  fc_dim: 720

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 20
  start_epoch: 0
  epoch_iters: 1200  # i guess this is the number of images we have available for training. Default was 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 4
  disp_iter: 20
  seed: 304

VAL:
  visualize: True  # visualize validation results. Default was False
  checkpoint: "epoch_7.pth"

TEST:
  checkpoint: "epoch_7.pth"
  result: "./"

DIR: "ckpt/ade20k-hrnetv2-c1-edu"
